### ISSUE TITLE
No Materials and broken files

### ISSUE THREAD

**Issue by ZsoltHevesi** [VOptimizer/VoxelOptimizer#2]
When I save my exported .vox models with multiple materials to OBJ and check the file info, it always says there is only one Material ID?

When I save a regular .vox file (one that hasn't been exported to a new .vox), the .OBJ file is broken and can't be loaded with the regular Windows 3D viewer or into Godot.

Tested with both MagicaVoxel 0.99.7.1 and 0.99.6.4

**Comment by tostc** [comment]
Hey thanks for the report,

there is actually a problem with the Obj exporter. As a quick solution, you can use GLB export. This one works and also works with Godot.
Regarding your question about the material. I combine all materials where every attribute matches each other. As an example: you have 4 colored voxels with the standard material of Magicavoxel, this would be a material later. If you also have a metal material, this would be another material.

**Comment by ZsoltHevesi** [comment]
I tried to export as GLB, however when I open the Output folder and select GLB, for some reason the only option I can press is "Open" as if I'm inputting a file. Clicking this option says "Please select a file" even though I already have a .vox file in the Input

**Comment by tostc** [comment]
Did you maybe hit enter to open the dialog? Because if the open button was the last one you clicked, it will be clicked again. Also I don't now if tab index is correct in my app.

**Comment by tostc** [comment]
I've released a new version on itch. It contains a fix for the obj exporter. Please let me know if your issues are now gone.

**Comment by ZsoltHevesi** [comment]
It works now, thank you. A couple small issues though:
Exported OBJ .vox files with mutliple objects/layers, some of the voxels are in seemingly random positions and not lined up the way it is in MagicaVoxel. A simple fix to this though is to put everything into the same object, which is possible for me but might not be for others who are using multiple max sized objects next to each other.

Another thing (which may be harder to fix) is that the Greedy Mesh seems a little.. off. Here is a comparison of the results made with a similar tool I use in Blender:

VOptimizer:
![Screenshot (310)](https://github.com/VOptimizer/VoxelOptimizer/assets/124164938/6aebd55f-90f0-4e27-bcc8-db4cf50a2935)

Blender:
![Screenshot (309)](https://github.com/VOptimizer/VoxelOptimizer/assets/124164938/e137bb2f-b89f-43f0-9dae-39fc2b9faece)

Finally, it would be nice if this could create a Material ID for every different coloured voxel, irrespective of what they were set to in MagicaVoxel's renderer, it makes it easy to add your own colours and Materials in stuff like Godot.

I know there isn't much more I could ask of you and I wanted to say this is a really neat application. You got back to me with fixes super quickly as well, thank you!

**Comment by tostc** [comment]
I've fixed the issue with the messed up object positions. The new version is on itch.
To switch colors of your model it's easier to change the colorpalette (*.albedo.png) of the material. Since multiple materials, which are all doing the same,  for multiple faces produces more draw calls than just one material for all faces. Each drawcall impacts a little bit the performance of a game.

**Comment by ZsoltHevesi** [comment]
Your latest update now has OBJ exports fully functional, thank you! Big models load super quick and the advantage of having a program like this is that this version will always work with its respective file types. Also thank you for the info on material optimisations. Greedy mesh still seems to have its size limits, but it works well nonetheless.

Here are some examples of the final results I produced:
![Screenshot (313)](https://github.com/VOptimizer/VoxelOptimizer/assets/124164938/b8468208-cea1-4678-8d54-e74434955941)
![Screenshot (314)](https://github.com/VOptimizer/VoxelOptimizer/assets/124164938/13e7ae4c-92e9-45fb-82e1-8a7203579920)

I suppose that for stuff like player customizations, having everything as a material is better, however for stuff you don't need to change like buildings, albedo is definitely better.

**Comment by tostc** [comment]
Thats nice. I've added the thing with the greedy mesher to the enhancement list of V-Core. I close this issue since the exporter is fixed.

**Comment by tostc** [comment]
Just to let you know, the new version of the tool contains a new greedy mesher, which generates less in a chunk like pattern.
